FROM php:5.6-apache

RUN apt-get update -y && \
    apt-get install -y \
        git \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libonig-dev \
        libpng-dev \
        libzip-dev \
        openssl \
        unzip \
        vim \
        wget \
        zip && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean all

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install \
        gd \
        mbstring \
        mysqli \
        pdo \
        pdo_mysql \
        zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install channel://pecl.php.net/xdebug-2.5.5

COPY docker/apache/site.conf /etc/apache2/sites-available/000-default.conf
COPY docker/php/*.ini /usr/local/etc/php/conf.d/

WORKDIR /srv

RUN echo 'alias ll="ls -la --color"' >> ~/.bashrc
